validation: sovereign
version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
- name: validator1
  bonded: 100000000stake
- name: validator2
  bonded: 200000000stake
- name: validator3
  bonded: 300000000stake
